/**
 * public-api/registry.ts — ЕДИНЫЙ источник истины для публичного API Finkley.
 *
 * Декларативный реестр ресурсов. И сама Edge Function (index.ts), и публичная
 * страница документации (через discovery-эндпоинт GET /v1) читают этот реестр,
 * поэтому документация физически не может разойтись с реальным API.
 *
 * Колонки взяты дословно из apps/web/src/types/supabase.ts (сгенерированные
 * типы). Server-managed поля (id, salon_id, created_at, …) намеренно не входят
 * в create/update — даже если клиент их пришлёт, движок их выкинет.
 *
 * Принципы безопасности (см. decisions/032-public-api.md):
 *  - Каждый запрос жёстко ограничен салоном ключа (salonColumn / parentScope /
 *    bankScope). Клиент НЕ может задать salon_id.
 *  - Ресурсы со `salonColumn: null` скоупятся через проверенного родителя и
 *    в v1 доступны только на чтение.
 *  - RPC-аналитика — read-only; включены только функции без auth.uid()-guard
 *    (иначе вызов через service-role всегда падал бы с forbidden).
 *  - Глобальные/служебные таблицы (media_posts, api_keys, billing, secrets,
 *    audit, profiles, …) в реестр НЕ входят вовсе.
 */

export type ResourceKind = 'table' | 'rpc'

/** Маппинг query-параметра клиента на аргумент RPC. */
export type RpcArgMap = {
  /** имя query-параметра (from/to/limit/tz/horizon_days) */
  query: string
  /** имя аргумента функции (p_period_start, …) */
  rpcParam: string
  required?: boolean
  /** числовой аргумент (limit/horizon_days) */
  numeric?: boolean
}

/** Скоуп через родительскую запись (для таблиц без прямой колонки салона). */
export type ParentScope = {
  /** обязательный query-параметр с id родителя */
  param: string
  /** колонка на этой таблице для фильтра (обычно == param) */
  column: string
  /** родительская таблица для проверки принадлежности салону */
  parentTable: string
  /** колонка салона в родителе */
  parentSalonColumn: string
}

export type ResourceDef = {
  resource: string
  table: string
  kind: ResourceKind
  pk: string
  /** прямая колонка салона ('salon_id' | 'id') или null (parent/bank scope) */
  salonColumn: string | null
  softDeleteColumn: string | null
  read: string[]
  create: string[]
  update: string[]
  allowDelete: boolean
  /** колонки, по которым разрешён точный фильтр ?col=value */
  filters: string[]
  /** колонка для диапазона ?from=&to= (timestamp/date) или null */
  dateColumn: string | null
  defaultOrder: { column: string; ascending: boolean } | null
  /** колонки в целых минорных единицах (копейки/центы) */
  money: string[]
  /** обязательные поля при создании */
  required: string[]
  /** для kind==='rpc' */
  rpc?: { fn: string; salonArg: string; args: RpcArgMap[] }
  /** parent-scope для таблиц без прямой колонки салона */
  parentScope?: ParentScope
  /** спец-scope для банковских таблиц */
  bankScope?: 'accounts' | 'transactions'
  description: string
}

const order = (column: string, ascending = false) => ({ column, ascending })

export const RESOURCES: ResourceDef[] = [
  // ───────────────────────── Доходы и визиты ─────────────────────────
  {
    resource: 'visits',
    table: 'visits',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'staff_id',
      'client_id',
      'service_id',
      'service_name_snapshot',
      'visit_at',
      'amount_cents',
      'tip_cents',
      'discount_cents',
      'discount_reason',
      'payment_method',
      'status',
      'kind',
      'comment',
      'duration_min',
      'cash_register_id',
      'inventory_item_id',
      'source',
      'created_at',
      'updated_at',
    ],
    create: [
      'visit_at',
      'amount_cents',
      'tip_cents',
      'discount_cents',
      'discount_reason',
      'client_id',
      'staff_id',
      'service_id',
      'service_name_snapshot',
      'payment_method',
      'status',
      'kind',
      'comment',
      'duration_min',
      'cash_register_id',
      'inventory_item_id',
    ],
    update: [
      'visit_at',
      'amount_cents',
      'tip_cents',
      'discount_cents',
      'discount_reason',
      'client_id',
      'staff_id',
      'service_id',
      'service_name_snapshot',
      'payment_method',
      'status',
      'kind',
      'comment',
      'duration_min',
      'cash_register_id',
      'inventory_item_id',
    ],
    allowDelete: true,
    filters: ['status', 'staff_id', 'client_id', 'service_id', 'payment_method', 'kind'],
    dateColumn: 'visit_at',
    defaultOrder: order('visit_at'),
    money: ['amount_cents', 'tip_cents', 'discount_cents'],
    required: ['visit_at', 'amount_cents'],
    description: 'Визиты/записи — основная выручка салона. Суммы в копейках.',
  },
  {
    resource: 'other-incomes',
    table: 'other_incomes',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'category_id',
      'income_at',
      'amount_cents',
      'payment_method',
      'cash_register_id',
      'comment',
      'receipt_url',
      'payer_name',
      'sub_article',
      'source',
      'created_at',
      'updated_at',
    ],
    create: [
      'income_at',
      'amount_cents',
      'category_id',
      'payment_method',
      'cash_register_id',
      'comment',
      'payer_name',
      'sub_article',
    ],
    update: [
      'income_at',
      'amount_cents',
      'category_id',
      'payment_method',
      'cash_register_id',
      'comment',
      'payer_name',
      'sub_article',
    ],
    allowDelete: true,
    filters: ['category_id', 'payment_method'],
    dateColumn: 'income_at',
    defaultOrder: order('income_at'),
    money: ['amount_cents'],
    required: ['income_at', 'amount_cents'],
    description: 'Прочие доходы (не визиты): бонусы, продажи, возвраты.',
  },
  {
    resource: 'other-income-categories',
    table: 'other_income_categories',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'name', 'is_archived', 'is_system', 'sort_order', 'parent_id'],
    create: ['name', 'sort_order', 'parent_id'],
    update: ['name', 'is_archived', 'sort_order', 'parent_id'],
    allowDelete: true,
    filters: ['is_archived', 'is_system', 'parent_id'],
    dateColumn: null,
    defaultOrder: order('sort_order', true),
    money: [],
    required: ['name'],
    description: 'Категории прочих доходов (дерево через parent_id).',
  },
  {
    resource: 'payment-methods',
    table: 'payment_methods',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'code', 'label', 'is_archived', 'is_system', 'sort_order'],
    create: ['code', 'label', 'sort_order'],
    update: ['label', 'is_archived', 'sort_order'],
    allowDelete: true,
    filters: ['is_archived', 'is_system', 'code'],
    dateColumn: null,
    defaultOrder: order('sort_order', true),
    money: [],
    required: ['code', 'label'],
    description: 'Способы оплаты салона (code: cash|card|transfer|online|mixed).',
  },
  {
    resource: 'visit-templates',
    table: 'visit_templates',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'client_id',
      'service_id',
      'staff_id',
      'amount_cents',
      'recurrence_days',
      'next_due_at',
      'paused_at',
      'created_at',
      'updated_at',
    ],
    create: [
      'client_id',
      'service_id',
      'staff_id',
      'amount_cents',
      'recurrence_days',
      'next_due_at',
    ],
    update: [
      'client_id',
      'service_id',
      'staff_id',
      'amount_cents',
      'recurrence_days',
      'next_due_at',
      'paused_at',
    ],
    allowDelete: true,
    filters: ['client_id', 'service_id', 'staff_id'],
    dateColumn: 'next_due_at',
    defaultOrder: order('next_due_at', true),
    money: ['amount_cents'],
    required: ['client_id', 'recurrence_days', 'next_due_at'],
    description: 'Шаблоны повторяющихся визитов (абонементы).',
  },
  // ───────────────────────── Расходы и финансы ─────────────────────────
  {
    resource: 'expenses',
    table: 'expenses',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'category_id',
      'expense_at',
      'amount_cents',
      'paid_amount_cents',
      'payment_method',
      'description',
      'document_number',
      'invoice_number',
      'counterparty_id',
      'cash_register_id',
      'comment',
      'source',
      'receipt_url',
      'recurrence',
      'next_occurrence_at',
      'recurrence_parent_id',
      'is_recurring',
      'payroll_staff_id',
      'payroll_kind',
      'payroll_period_start',
      'payroll_period_end',
      'contractor_name',
      'sub_article',
      'bank_transaction_id',
      'external_id',
      'created_at',
      'updated_at',
    ],
    create: [
      'expense_at',
      'amount_cents',
      'paid_amount_cents',
      'category_id',
      'payment_method',
      'description',
      'document_number',
      'invoice_number',
      'counterparty_id',
      'cash_register_id',
      'comment',
      'recurrence',
      'next_occurrence_at',
      'is_recurring',
      'payroll_staff_id',
      'payroll_kind',
      'payroll_period_start',
      'payroll_period_end',
      'contractor_name',
      'sub_article',
      'receipt_url',
      'external_id',
    ],
    update: [
      'expense_at',
      'amount_cents',
      'paid_amount_cents',
      'category_id',
      'payment_method',
      'description',
      'document_number',
      'invoice_number',
      'counterparty_id',
      'cash_register_id',
      'comment',
      'recurrence',
      'next_occurrence_at',
      'is_recurring',
      'payroll_staff_id',
      'payroll_kind',
      'payroll_period_start',
      'payroll_period_end',
      'contractor_name',
      'sub_article',
      'receipt_url',
      'external_id',
    ],
    allowDelete: true,
    filters: ['category_id', 'payment_method', 'payroll_staff_id', 'counterparty_id', 'recurrence'],
    dateColumn: 'expense_at',
    defaultOrder: order('expense_at'),
    money: ['amount_cents', 'paid_amount_cents'],
    required: ['expense_at', 'amount_cents', 'category_id'],
    description: 'Расходы салона. Суммы в копейках.',
  },
  {
    resource: 'expense-categories',
    table: 'expense_categories',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'name',
      'kind',
      'is_archived',
      'is_payroll',
      'is_system',
      'monthly_budget_cents',
      'monthly_budget_pct',
      'sort_order',
      'created_at',
    ],
    create: [
      'name',
      'kind',
      'is_archived',
      'is_payroll',
      'monthly_budget_cents',
      'monthly_budget_pct',
      'sort_order',
    ],
    update: [
      'name',
      'kind',
      'is_archived',
      'is_payroll',
      'monthly_budget_cents',
      'monthly_budget_pct',
      'sort_order',
    ],
    allowDelete: true,
    filters: ['kind', 'is_archived', 'is_payroll', 'is_system'],
    dateColumn: null,
    defaultOrder: order('sort_order', true),
    money: ['monthly_budget_cents'],
    required: ['name'],
    description: 'Категории расходов. is_system — встроенные (только чтение этого флага).',
  },
  {
    resource: 'scheduled-payments',
    table: 'scheduled_payments',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'category_id',
      'due_date',
      'amount_cents',
      'vendor_name',
      'invoice_number',
      'comment',
      'status',
      'paid_at',
      'paid_expense_id',
      'source',
      'external_id',
      'created_at',
      'updated_at',
    ],
    create: [
      'due_date',
      'amount_cents',
      'category_id',
      'vendor_name',
      'invoice_number',
      'comment',
      'external_id',
    ],
    update: [
      'due_date',
      'amount_cents',
      'category_id',
      'vendor_name',
      'invoice_number',
      'comment',
      'status',
      'paid_at',
      'paid_expense_id',
    ],
    allowDelete: true,
    filters: ['category_id', 'status'],
    dateColumn: 'due_date',
    defaultOrder: order('due_date', true),
    money: ['amount_cents'],
    required: ['due_date', 'amount_cents'],
    description: 'Платёжный календарь (предстоящие платежи). status: pending|paid.',
  },
  // ───────────────────────── Клиенты и отзывы ─────────────────────────
  {
    resource: 'clients',
    table: 'clients',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'name',
      'phone',
      'email',
      'birthday',
      'source',
      'tags',
      'notes',
      'socials',
      'discount_percent',
      'visit_count',
      'total_revenue_cents',
      'last_visit_at',
      'created_at',
      'updated_at',
    ],
    create: [
      'name',
      'phone',
      'email',
      'birthday',
      'source',
      'tags',
      'notes',
      'socials',
      'discount_percent',
    ],
    update: [
      'name',
      'phone',
      'email',
      'birthday',
      'source',
      'tags',
      'notes',
      'socials',
      'discount_percent',
    ],
    allowDelete: true,
    filters: ['phone', 'email', 'source'],
    dateColumn: 'created_at',
    defaultOrder: order('created_at'),
    money: ['total_revenue_cents'],
    required: ['name'],
    description:
      'Клиенты салона. visit_count/total_revenue_cents/last_visit_at — вычисляемые (read-only).',
  },
  {
    resource: 'reviews',
    table: 'reviews',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'source',
      'visibility',
      'rating',
      'body',
      'author_name',
      'client_id',
      'staff_id',
      'visit_id',
      'external_id',
      'external_url',
      'read_at',
      'posted_at',
      'created_at',
      'reply_text',
      'reply_author',
      'reply_posted_at',
    ],
    create: [
      'visibility',
      'rating',
      'body',
      'author_name',
      'client_id',
      'staff_id',
      'visit_id',
      'posted_at',
    ],
    update: [
      'visibility',
      'rating',
      'body',
      'author_name',
      'read_at',
      'reply_text',
      'reply_author',
      'reply_posted_at',
    ],
    allowDelete: true,
    filters: ['source', 'visibility', 'client_id', 'staff_id', 'rating'],
    dateColumn: 'created_at',
    defaultOrder: order('created_at'),
    money: [],
    required: ['rating'],
    description: 'Отзывы. source: internal|booksy|google (внешние синкаются сервером).',
  },
  {
    resource: 'review-requests',
    table: 'review_requests',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'client_id',
      'visit_id',
      'created_at',
      'expires_at',
      'opened_at',
      'submitted_at',
    ],
    create: ['client_id', 'visit_id', 'expires_at'],
    update: ['expires_at'],
    allowDelete: true,
    filters: ['client_id', 'visit_id'],
    dateColumn: 'created_at',
    defaultOrder: order('created_at'),
    money: [],
    required: ['client_id'],
    description: 'Запросы отзыва клиентам. Поле token (секрет) не отдаётся.',
  },
  // ───────────────────────── Каталог услуг ─────────────────────────
  {
    resource: 'services',
    table: 'services',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'name',
      'category_id',
      'default_price_cents',
      'default_duration_min',
      'cost_cents',
      'is_archived',
      'external_source',
      'external_id',
      'staff_count_required',
      'avg_service_hours',
      'staff_work_hours_per_day',
      'staff_work_days_per_month',
      'utilization_pct',
      'avg_check_cents',
      'staff_payout_pct',
      'materials_pct',
      'created_at',
      'updated_at',
    ],
    create: ['name', 'category_id', 'default_price_cents', 'default_duration_min', 'cost_cents'],
    update: [
      'name',
      'category_id',
      'default_price_cents',
      'default_duration_min',
      'cost_cents',
      'is_archived',
      'staff_count_required',
      'avg_service_hours',
      'staff_work_hours_per_day',
      'staff_work_days_per_month',
      'utilization_pct',
      'avg_check_cents',
      'staff_payout_pct',
      'materials_pct',
    ],
    allowDelete: true,
    filters: ['category_id', 'is_archived'],
    dateColumn: null,
    defaultOrder: order('name', true),
    money: ['default_price_cents', 'cost_cents', 'avg_check_cents'],
    required: ['name'],
    description: 'Каталог услуг. Цены/себестоимость в копейках.',
  },
  {
    resource: 'service-categories',
    table: 'service_categories',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'name',
      'sort_order',
      'is_archived',
      'return_period_days',
      'created_at',
      'updated_at',
    ],
    create: ['name', 'sort_order'],
    update: ['name', 'sort_order', 'is_archived', 'return_period_days'],
    allowDelete: true,
    filters: ['is_archived'],
    dateColumn: null,
    defaultOrder: order('sort_order', true),
    money: [],
    required: ['name'],
    description: 'Категории услуг.',
  },
  {
    resource: 'service-materials',
    table: 'service_materials',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['id', 'service_id', 'material_id', 'quantity', 'notes', 'created_at'],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['material_id'],
    dateColumn: null,
    defaultOrder: order('created_at'),
    money: [],
    required: [],
    parentScope: {
      param: 'service_id',
      column: 'service_id',
      parentTable: 'services',
      parentSalonColumn: 'salon_id',
    },
    description: 'Материалы услуги (read-only v1). Обязателен ?service_id= из вашего салона.',
  },
  {
    resource: 'staff-service-overrides',
    table: 'staff_service_overrides',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['id', 'staff_id', 'service_id', 'payout_percent'],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['service_id'],
    dateColumn: null,
    defaultOrder: null,
    money: [],
    required: [],
    parentScope: {
      param: 'staff_id',
      column: 'staff_id',
      parentTable: 'staff',
      parentSalonColumn: 'salon_id',
    },
    description:
      'Переопределения % выплат мастера по услуге (read-only v1). Обязателен ?staff_id=.',
  },
  // ───────────────────────── Мастера и выплаты ─────────────────────────
  {
    resource: 'staff',
    table: 'staff',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'full_name',
      'email',
      'avatar_url',
      'is_active',
      'payout_scheme',
      'payout_percent',
      'payout_fixed_cents',
      'chair_rent_cents',
      'retail_payout_enabled',
      'retail_payout_percent',
      'visible_on_calendar',
      'weekly_schedule',
      'retention_window_days',
      'created_at',
      'updated_at',
    ],
    create: [
      'full_name',
      'email',
      'payout_scheme',
      'payout_percent',
      'payout_fixed_cents',
      'chair_rent_cents',
      'retail_payout_enabled',
      'retail_payout_percent',
      'weekly_schedule',
      'retention_window_days',
    ],
    update: [
      'full_name',
      'email',
      'avatar_url',
      'is_active',
      'payout_scheme',
      'payout_percent',
      'payout_fixed_cents',
      'chair_rent_cents',
      'retail_payout_enabled',
      'retail_payout_percent',
      'visible_on_calendar',
      'weekly_schedule',
      'retention_window_days',
    ],
    allowDelete: true,
    filters: ['is_active', 'payout_scheme'],
    dateColumn: null,
    defaultOrder: order('full_name', true),
    money: ['payout_fixed_cents', 'chair_rent_cents'],
    required: ['full_name'],
    description: 'Мастера. payout_scheme определяет используемые поля выплат.',
  },
  {
    resource: 'staff-services',
    table: 'staff_services',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'staff_id', 'service_id', 'created_at'],
    create: ['staff_id', 'service_id'],
    update: [],
    allowDelete: true,
    filters: ['staff_id', 'service_id'],
    dateColumn: 'created_at',
    defaultOrder: order('created_at'),
    money: [],
    required: ['staff_id', 'service_id'],
    description: 'Какие услуги выполняет мастер (связь мастер↔услуга). Фильтр ?staff_id=.',
  },
  {
    resource: 'staff-time-blocks',
    table: 'staff_time_blocks',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'staff_id',
      'kind',
      'starts_at',
      'ends_at',
      'label',
      'created_at',
      'updated_at',
    ],
    create: ['staff_id', 'kind', 'starts_at', 'ends_at', 'label'],
    update: ['staff_id', 'kind', 'starts_at', 'ends_at', 'label'],
    allowDelete: true,
    filters: ['staff_id', 'kind'],
    dateColumn: 'starts_at',
    defaultOrder: order('starts_at'),
    money: [],
    required: ['staff_id', 'kind', 'starts_at', 'ends_at'],
    description: 'Блокировки времени мастера (отпуска, резервы).',
  },
  {
    resource: 'payouts',
    table: 'payouts',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'staff_id',
      'period_start',
      'period_end',
      'status',
      'total_revenue_cents',
      'total_payout_cents',
      'net_payout_cents',
      'total_advances_cents',
      'total_deductions_cents',
      'paid_at',
      'comment',
      'created_at',
      'updated_at',
    ],
    create: [],
    update: ['status', 'paid_at', 'comment'],
    allowDelete: false,
    filters: ['staff_id', 'status'],
    dateColumn: 'period_start',
    defaultOrder: order('period_start'),
    money: [
      'total_revenue_cents',
      'total_payout_cents',
      'net_payout_cents',
      'total_advances_cents',
      'total_deductions_cents',
    ],
    required: [],
    description:
      'Расчётные ведомости. Суммы вычисляются (read-only); можно менять status/paid_at/comment.',
  },
  {
    resource: 'payout-lines',
    table: 'payout_lines',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['id', 'payout_id', 'line_type', 'description', 'amount_cents', 'visit_id'],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['line_type'],
    dateColumn: null,
    defaultOrder: null,
    money: ['amount_cents'],
    required: [],
    parentScope: {
      param: 'payout_id',
      column: 'payout_id',
      parentTable: 'payouts',
      parentSalonColumn: 'salon_id',
    },
    description: 'Строки ведомости (read-only). Обязателен ?payout_id= из вашего салона.',
  },
  // ───────────────────────── Касса (read-only v1) ─────────────────────────
  {
    resource: 'cash-shifts',
    table: 'cash_shifts',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'opened_at',
      'opening_amount_cents',
      'opening_comment',
      'closed_at',
      'actual_cash_cents',
      'actual_card_cents',
      'expected_cash_cents',
      'expected_card_cents',
      'diff_cash_cents',
      'diff_card_cents',
      'close_comment',
      'discrepancy_reason',
      'status',
      'created_at',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['status'],
    dateColumn: 'opened_at',
    defaultOrder: order('opened_at'),
    money: [
      'opening_amount_cents',
      'actual_cash_cents',
      'actual_card_cents',
      'expected_cash_cents',
      'expected_card_cents',
      'diff_cash_cents',
      'diff_card_cents',
    ],
    required: [],
    description: 'Кассовые смены (read-only v1; открытие/закрытие — в приложении).',
  },
  {
    resource: 'cash-transfers',
    table: 'cash_transfers',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'salon_id',
      'from_register_id',
      'to_register_id',
      'amount_cents',
      'comment',
      'transferred_at',
      'reversal_of',
      'created_at',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['from_register_id', 'to_register_id'],
    dateColumn: 'transferred_at',
    defaultOrder: order('transferred_at'),
    money: ['amount_cents'],
    required: [],
    description: 'Переводы между кассами (read-only v1; создаются через RPC с проверкой баланса).',
  },
  // ───────────────────────── Склад ─────────────────────────
  {
    resource: 'inventory-items',
    table: 'inventory_items',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'name',
      'unit',
      'sku',
      'category',
      'current_stock',
      'min_stock',
      'cost_per_unit_cents',
      'supplier',
      'is_archived',
      'notes',
      'created_at',
      'updated_at',
    ],
    create: [
      'name',
      'unit',
      'sku',
      'category',
      'min_stock',
      'cost_per_unit_cents',
      'supplier',
      'notes',
    ],
    update: [
      'name',
      'unit',
      'sku',
      'category',
      'min_stock',
      'cost_per_unit_cents',
      'supplier',
      'notes',
      'is_archived',
    ],
    allowDelete: true,
    filters: ['category', 'is_archived'],
    dateColumn: null,
    defaultOrder: order('name', true),
    money: ['cost_per_unit_cents'],
    required: ['name'],
    description:
      'Складские позиции. current_stock меняется ТОЛЬКО движениями склада (RPC) — на create стартует с 0, при update недоступен (сохраняем аудит-трейл).',
  },
  {
    resource: 'inventory-transactions',
    table: 'inventory_transactions',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'material_id',
      'type',
      'quantity',
      'prev_stock',
      'cost_cents',
      'visit_id',
      'notes',
      'created_at',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['material_id', 'type', 'visit_id'],
    dateColumn: 'created_at',
    defaultOrder: order('created_at'),
    money: ['cost_cents'],
    required: [],
    description: 'Движения по складу (read-only; создаются RPC inventory_apply_tx/stocktake).',
  },
  // ───────────────────────── Банк (read-only) ─────────────────────────
  {
    resource: 'bank-accounts',
    table: 'bank_accounts',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'id',
      'connection_id',
      'external_id',
      'iban',
      'name',
      'currency',
      'is_active',
      'created_at',
      'updated_at',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['connection_id', 'is_active'],
    dateColumn: null,
    defaultOrder: order('created_at'),
    money: [],
    required: [],
    bankScope: 'accounts',
    description: 'Банковские счета (read-only, синкаются из банка).',
  },
  {
    resource: 'bank-transactions',
    table: 'bank_transactions',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'id',
      'account_id',
      'external_id',
      'type',
      'amount_cents',
      'currency',
      'description',
      'counterparty',
      'executed_at',
      'expense_id',
      'linked_visit_id',
      'linked_other_income_id',
      'needs_review',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['account_id', 'type', 'needs_review'],
    dateColumn: 'executed_at',
    defaultOrder: order('executed_at'),
    money: ['amount_cents'],
    required: [],
    bankScope: 'transactions',
    description: 'Банковские транзакции (read-only, синкаются из банка).',
  },
  // ───────────────────────── Контрагенты ─────────────────────────
  {
    resource: 'counterparties',
    table: 'counterparties',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'archived_at',
    read: [
      'id',
      'salon_id',
      'name',
      'nip',
      'address',
      'category_id',
      'notes',
      'archived_at',
      'created_at',
      'updated_at',
    ],
    create: ['name', 'nip', 'address', 'category_id', 'notes'],
    update: ['name', 'nip', 'address', 'category_id', 'notes', 'archived_at'],
    allowDelete: true,
    filters: ['category_id'],
    dateColumn: 'created_at',
    defaultOrder: order('name', true),
    money: [],
    required: ['name'],
    description: 'Контрагенты (поставщики/подрядчики). archived_at — мягкое удаление.',
  },
  {
    resource: 'counterparty-categories',
    table: 'counterparty_categories',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: 'archived_at',
    read: ['id', 'salon_id', 'name', 'archived_at', 'created_at'],
    create: ['name'],
    update: ['name', 'archived_at'],
    allowDelete: true,
    filters: [],
    dateColumn: 'created_at',
    defaultOrder: order('name', true),
    money: [],
    required: ['name'],
    description: 'Категории контрагентов.',
  },
  // ───────────────────────── Салон, расписание, контент ─────────────────────────
  {
    resource: 'salons',
    table: 'salons',
    kind: 'table',
    pk: 'id',
    salonColumn: 'id',
    softDeleteColumn: 'deleted_at',
    read: [
      'id',
      'name',
      'country_code',
      'currency',
      'locale',
      'timezone',
      'salon_type',
      'address',
      'city',
      'lat',
      'lng',
      'logo_url',
      'booksy_url',
      'facebook_url',
      'instagram_url',
      'google_place_id',
      'google_place_url',
      'benchmarks_opt_in',
      'cash_discipline_enabled',
      'opening_hours',
      'opening_cash_balance_cents',
      'churn_window_days',
      'retention_window_days',
      'created_at',
      'updated_at',
    ],
    create: [],
    update: [
      'name',
      'address',
      'city',
      'lat',
      'lng',
      'logo_url',
      'booksy_url',
      'facebook_url',
      'instagram_url',
      'google_place_id',
      'google_place_url',
      'benchmarks_opt_in',
      'cash_discipline_enabled',
      'opening_hours',
      'churn_window_days',
      'retention_window_days',
    ],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['opening_cash_balance_cents'],
    required: [],
    description:
      'Профиль салона (один — ваш). Чувствительные настройки (бухгалтерия, биллинг) не отдаются.',
  },
  {
    resource: 'salon-metrics',
    table: 'own_salon_metrics',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'kind', 'source', 'data', 'snapshot_date', 'created_at'],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['kind', 'source'],
    dateColumn: 'snapshot_date',
    defaultOrder: order('snapshot_date'),
    money: [],
    required: [],
    description:
      'Метрики салона из синков (read-only). kind=rating → data {rating, count} по source (google/booksy) — агрегатный рейтинг; kind=content → подписчики/посты. Сами отзывы — в ресурсе reviews (?source=google|booksy).',
  },
  {
    resource: 'salon-holidays',
    table: 'salon_holidays',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'date', 'label', 'is_recurring', 'country_code', 'created_at'],
    create: ['date', 'label', 'is_recurring', 'country_code'],
    update: ['date', 'label', 'is_recurring', 'country_code'],
    allowDelete: true,
    filters: ['is_recurring'],
    dateColumn: 'date',
    defaultOrder: order('date', true),
    money: [],
    required: ['date', 'label'],
    description: 'Выходные/праздники салона.',
  },
  {
    resource: 'salon-kb-articles',
    table: 'salon_kb_articles',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: ['id', 'salon_id', 'section', 'title', 'body', 'sort_order', 'created_at', 'updated_at'],
    create: ['section', 'title', 'body', 'sort_order'],
    update: ['section', 'title', 'body', 'sort_order'],
    allowDelete: true,
    filters: ['section'],
    dateColumn: null,
    defaultOrder: order('sort_order', true),
    money: [],
    required: ['section', 'title', 'body'],
    description: 'База знаний салона (внутренние статьи/регламенты).',
  },
  {
    resource: 'competitors',
    table: 'competitors',
    kind: 'table',
    pk: 'id',
    salonColumn: 'salon_id',
    softDeleteColumn: null,
    read: [
      'id',
      'salon_id',
      'name',
      'is_archived',
      'is_auto_picked',
      'google_place_id',
      'google_place_url',
      'facebook_url',
      'instagram_url',
      'booksy_url',
      'content_followers',
      'content_posts',
      'content_posts_per_month',
      'content_fb_likes',
      'content_updated_at',
      'created_at',
      'updated_at',
    ],
    create: [
      'name',
      'google_place_id',
      'google_place_url',
      'facebook_url',
      'instagram_url',
      'booksy_url',
    ],
    update: [
      'name',
      'is_archived',
      'google_place_id',
      'google_place_url',
      'facebook_url',
      'instagram_url',
      'booksy_url',
    ],
    allowDelete: true,
    filters: ['is_archived', 'is_auto_picked'],
    dateColumn: null,
    defaultOrder: order('name', true),
    money: [],
    required: ['name'],
    description: 'Конкуренты (мониторинг). Метрики соцсетей обновляются сервером.',
  },
  {
    resource: 'competitor-snapshots',
    table: 'competitor_snapshots',
    kind: 'table',
    pk: 'id',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['id', 'competitor_id', 'snapshot_date', 'kind', 'source', 'data', 'created_at'],
    create: [],
    update: [],
    allowDelete: false,
    filters: ['kind', 'source'],
    dateColumn: 'snapshot_date',
    defaultOrder: order('snapshot_date'),
    money: [],
    required: [],
    parentScope: {
      param: 'competitor_id',
      column: 'competitor_id',
      parentTable: 'competitors',
      parentSalonColumn: 'salon_id',
    },
    description:
      'История метрик конкурента (read-only). Обязателен ?competitor_id= из вашего салона.',
  },
  // ───────────────────────── Аналитика (RPC, read-only) ─────────────────────────
  {
    resource: 'dashboard-kpis',
    table: 'dashboard_kpis',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['revenue_cents', 'expense_cents', 'profit_cents', 'visits_count'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents', 'expense_cents', 'profit_cents'],
    required: [],
    rpc: {
      fn: 'dashboard_kpis',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
      ],
    },
    description: 'Сводные KPI за период. Параметры: from, to (YYYY-MM-DD), обязательны.',
  },
  {
    resource: 'revenue-by-day',
    table: 'revenue_by_day',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['day', 'revenue_cents', 'visits_count'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents'],
    required: [],
    rpc: {
      fn: 'revenue_by_day',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
        { query: 'tz', rpcParam: 'p_timezone' },
      ],
    },
    description: 'Выручка по дням. Параметры: from, to (обязательны), tz (IANA, опц.).',
  },
  {
    resource: 'cash-flow-daily',
    table: 'cash_flow_daily',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['day', 'inflow_cents', 'outflow_cents', 'net_cents'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['inflow_cents', 'outflow_cents', 'net_cents'],
    required: [],
    rpc: {
      fn: 'cash_flow_daily',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_from', required: true },
        { query: 'to', rpcParam: 'p_to', required: true },
      ],
    },
    description: 'Денежный поток по дням (приток/отток/нетто). Параметры: from, to.',
  },
  {
    resource: 'analytics-revenue-by-payment',
    table: 'analytics_revenue_by_payment',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['payment_method', 'revenue_cents', 'visits_count'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents'],
    required: [],
    rpc: {
      fn: 'analytics_revenue_by_payment',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
      ],
    },
    description: 'Выручка по способам оплаты. Параметры: from, to.',
  },
  {
    resource: 'analytics-visits-heatmap',
    table: 'analytics_visits_heatmap',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['dow', 'hour_of_day', 'visits_count', 'revenue_cents'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents'],
    required: [],
    rpc: {
      fn: 'analytics_visits_heatmap',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
        { query: 'tz', rpcParam: 'p_timezone' },
      ],
    },
    description: 'Тепловая карта визитов по дню недели и часу. Параметры: from, to, tz (опц.).',
  },
  {
    resource: 'top-clients-by-revenue',
    table: 'top_clients_by_revenue',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'client_id',
      'full_name',
      'phone',
      'email',
      'revenue_cents',
      'visit_count',
      'last_visit_at',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents'],
    required: [],
    rpc: {
      fn: 'top_clients_by_revenue',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_start', required: true },
        { query: 'to', rpcParam: 'p_end', required: true },
        { query: 'limit', rpcParam: 'p_limit', numeric: true },
      ],
    },
    description: 'Топ клиентов по выручке. Параметры: from, to, limit (опц.).',
  },
  {
    resource: 'top-services-by-revenue',
    table: 'top_services_by_revenue',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'service_id',
      'service_name',
      'revenue_cents',
      'cost_cents',
      'margin_cents',
      'margin_pct',
      'visits_count',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents', 'cost_cents', 'margin_cents'],
    required: [],
    rpc: {
      fn: 'top_services_by_revenue',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
        { query: 'limit', rpcParam: 'p_limit', numeric: true },
      ],
    },
    description: 'Топ услуг по выручке/марже. Параметры: from, to, limit (опц.).',
  },
  {
    resource: 'top-staff-by-revenue',
    table: 'top_staff_by_revenue',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['staff_id', 'full_name', 'revenue_cents'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_cents'],
    required: [],
    rpc: {
      fn: 'top_staff_by_revenue',
      salonArg: 'p_salon_id',
      args: [
        { query: 'from', rpcParam: 'p_period_start', required: true },
        { query: 'to', rpcParam: 'p_period_end', required: true },
        { query: 'limit', rpcParam: 'p_limit', numeric: true },
      ],
    },
    description: 'Топ мастеров по выручке. Параметры: from, to, limit (опц.).',
  },
  {
    resource: 'weekly-digest-kpis',
    table: 'weekly_digest_kpis',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'period_start',
      'period_end',
      'revenue_cents',
      'prev_revenue_cents',
      'expense_cents',
      'profit_cents',
      'visits_count',
      'top_service_name',
      'top_service_revenue_cents',
      'top_staff_name',
      'top_staff_revenue_cents',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: [
      'revenue_cents',
      'prev_revenue_cents',
      'expense_cents',
      'profit_cents',
      'top_service_revenue_cents',
      'top_staff_revenue_cents',
    ],
    required: [],
    rpc: { fn: 'weekly_digest_kpis', salonArg: 'p_salon_id', args: [] },
    description: 'Недельная сводка (выручка, прибыль, топ-услуга/мастер). Без параметров.',
  },
  {
    resource: 'category-budgets-progress',
    table: 'category_budgets_progress',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: ['category_id', 'name', 'monthly_budget_cents', 'current_month_cents', 'progress_pct'],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['monthly_budget_cents', 'current_month_cents'],
    required: [],
    rpc: { fn: 'category_budgets_progress', salonArg: 'p_salon_id', args: [] },
    description: 'Бюджеты категорий расходов vs факт за текущий месяц. Без параметров.',
  },
  {
    resource: 'client-ltv-metrics',
    table: 'client_ltv_metrics',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'client_id',
      'revenue_ltv_cents',
      'gross_ltv_cents',
      'customer_lifetime_months',
      'visits_count',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: ['revenue_ltv_cents', 'gross_ltv_cents'],
    required: [],
    rpc: { fn: 'client_ltv_metrics', salonArg: 'p_salon_id', args: [] },
    description: 'LTV-метрики по клиентам (revenue/gross LTV, срок жизни). Без параметров.',
  },
  {
    resource: 'upcoming-visit-templates',
    table: 'upcoming_visit_templates',
    kind: 'rpc',
    pk: '',
    salonColumn: null,
    softDeleteColumn: null,
    read: [
      'id',
      'client_id',
      'client_name',
      'staff_id',
      'staff_name',
      'service_id',
      'service_name',
      'recurrence_days',
      'next_due_at',
      'days_until',
    ],
    create: [],
    update: [],
    allowDelete: false,
    filters: [],
    dateColumn: null,
    defaultOrder: null,
    money: [],
    required: [],
    rpc: {
      fn: 'upcoming_visit_templates',
      salonArg: 'p_salon_id',
      args: [{ query: 'horizon_days', rpcParam: 'p_horizon_days', numeric: true }],
    },
    description: 'Предстоящие повторные визиты в горизонте. Параметр: horizon_days (опц., дней).',
  },
]

export function findResource(slug: string): ResourceDef | undefined {
  return RESOURCES.find((r) => r.resource === slug)
}

/**
 * Публичный каталог для discovery-эндпоинта и страницы документации.
 * Не раскрывает ничего секретного — только форму API.
 */
export function buildCatalog() {
  return {
    version: 'v1',
    money_note: 'Все суммы (*_cents) — целые минорные единицы (копейки/центы).',
    auth: 'Authorization: Bearer <fnk_live_…> или заголовок x-api-key.',
    scopes: ['read', 'write'],
    pagination: { default_limit: 50, max_limit: 200, params: ['limit', 'offset'] },
    resources: RESOURCES.map((r) => {
      const methods: string[] = ['GET']
      if (r.kind === 'table') {
        if (r.create.length) methods.push('POST')
        if (r.update.length) methods.push('PATCH')
        if (r.allowDelete) methods.push('DELETE')
      }
      return {
        resource: r.resource,
        kind: r.kind,
        path: `/v1/${r.resource}`,
        methods,
        description: r.description,
        readable_fields: r.read,
        writable_fields_create: r.create,
        writable_fields_update: r.update,
        required_on_create: r.required,
        filters: r.filters,
        date_range: r.dateColumn ? ['from', 'to'] : [],
        money_fields: r.money,
        rpc_params: r.rpc ? r.rpc.args.map((a) => ({ name: a.query, required: !!a.required })) : [],
        parent_filter: r.parentScope ? r.parentScope.param : r.bankScope ? null : null,
      }
    }),
  }
}
