-- bug a75ebedf — простой трекер действий пользователя для аналитики
-- usage паттернов. Owner может потом увидеть к какому функционалу юзеры
-- активно ходят, что игнорируют.
--
-- НЕ замена Google Analytics — это первичный лог для product-decisions.
-- Хранит min поля: user_id, salon_id, action_kind, target, метаданные.
-- TTL = 90 дней (cleanup в daily-cron).

create table if not exists user_actions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  salon_id uuid references salons(id) on delete cascade,
  action_kind text not null,           -- 'page_view' | 'click' | 'feature_use'
  target text,                          -- '/dashboard', 'btn:add_expense', 'feature:bank_link'
  metadata jsonb,                       -- любые дополнительные поля
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_user_actions_salon_time
  on user_actions(salon_id, occurred_at desc);
create index if not exists idx_user_actions_user_time
  on user_actions(user_id, occurred_at desc);
create index if not exists idx_user_actions_kind
  on user_actions(action_kind, occurred_at desc);

alter table user_actions enable row level security;

-- Юзер пишет только свои события (защита от подделки): user_id = auth.uid()
-- ИЛИ NULL (для анонимных событий).
create policy "user_actions_insert_own" on user_actions
  for insert to authenticated with check (
    user_id = auth.uid() or user_id is null
  );

-- Чтение: только owner/admin салона видит события своего салона.
create policy "user_actions_select_own_salon" on user_actions
  for select to authenticated using (
    exists (
      select 1 from salon_members sm
      where sm.salon_id = user_actions.salon_id
        and sm.user_id = auth.uid()
        and sm.role in ('owner', 'admin')
    )
  );

comment on table user_actions is
  'bug a75ebedf — трекер действий пользователя. Page views, clicks, feature use. '
  'TTL 90 дней (cleanup в daily-cron).';

-- Daily cleanup — удаляем старше 90 дней.
create or replace function public.cleanup_user_actions_old()
returns void
language sql
security definer
set search_path = public
as $$
  delete from user_actions where occurred_at < now() - interval '90 days';
$$;
